/** @type {import('tailwindcss').Config} */
// Material 3-style dark token system, ported directly from the provided
// design spec - not the shadcn CSS-variable/hsl() indirection used before,
// since this design is deliberately dark-only (no light-mode toggle),
// so hardcoded hex values are simpler and match the spec exactly.
module.exports = {
  darkMode: 'class',
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-bright': '#393841',
        'tertiary-fixed': '#ffdcc5',
        'outline-variant': '#464554',
        'inverse-primary': '#494bd6',
        'inverse-surface': '#e4e1ed',
        background: '#13131b',
        'error-container': '#93000a',
        'on-secondary-fixed-variant': '#00513c',
        error: '#ffb4ab',
        'on-surface': '#e4e1ed',
        'on-secondary-container': '#ceffe8',
        'on-primary-fixed-variant': '#2f2ebe',
        'secondary-fixed': '#92f6cf',
        primary: '#c0c1ff',
        'on-tertiary-container': '#452000',
        outline: '#908fa0',
        surface: '#13131b',
        'on-secondary-fixed': '#002116',
        'tertiary-container': '#d97721',
        'surface-tint': '#c0c1ff',
        'on-tertiary-fixed': '#301400',
        'on-tertiary-fixed-variant': '#703700',
        'primary-fixed': '#e1e0ff',
        secondary: '#75d9b3',
        'primary-fixed-dim': '#c0c1ff',
        'surface-container-low': '#1b1b23',
        'primary-container': '#8083ff',
        'secondary-fixed-dim': '#75d9b3',
        'tertiary-fixed-dim': '#ffb783',
        'on-tertiary': '#4f2500',
        'on-background': '#e4e1ed',
        'surface-container': '#1f1f27',
        'on-error-container': '#ffdad6',
        tertiary: '#ffb783',
        'on-primary-fixed': '#07006c',
        'surface-dim': '#13131b',
        'surface-variant': '#34343d',
        'surface-container-highest': '#34343d',
        'secondary-container': '#007f5f',
        'on-primary': '#1000a9',
        'inverse-on-surface': '#303038',
        'surface-container-lowest': '#0d0d15',
        'on-primary-container': '#0d0096',
        'surface-container-high': '#292932',
        'on-surface-variant': '#c7c4d7',
        'on-error': '#690005',
        'on-secondary': '#003828',
        // Sign-in page specific - a distinct accent for the pre-auth
        // experience, not used anywhere else in the app shell.
        'brand-indigo': '#6366f1',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'table-cell-padding': '8px 12px',
        xxl: '32px',
        sm: '8px',
        base: '4px',
        md: '12px',
        xs: '4px',
        lg: '16px',
        'layout-margin': '24px',
        xl: '24px',
      },
      fontFamily: {
        'code-sm': ['JetBrains Mono', 'monospace'],
        'display-lg': ['Hanken Grotesk', 'sans-serif'],
        'code-base': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'body-base': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'code-sm': ['11px', { lineHeight: '16px', fontWeight: '400' }],
        'display-lg': ['30px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'code-base': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-base': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
